# ---
# - hosts: localhost
#   vars:
#     git_name: "{{ ansible_user_gecos }}"
#     git_email: "{{ ansible_user_gecos | lower | regex_replace('\\s', '.') | regex_replace('[æå]', 'a') | regex_replace('ø', 'o') }}@spk.no"
#   tasks:
#     - name: Install git
#       package:
#         name: git
#         state: latest
#       become: true

#     # scope=system is the default
#     - name: Git credentials
#       debug:
#         msg: "name: '{{ git_name }}' email: '{{ git_email }}'"

#     - git_config:
#         name: user.name
#         value: "{{ git_name }}"
#         scope: global

#     - git_config:
#         name: user.email
#         value: "{{ git_email }}"
#         scope: global

#     - git_config:
#         name: alias.co
#         value: checkout
#         scope: global

#     - git_config:
#         name: alias.ci
#         value: commit
#         scope: global

#     - git_config:
#         name: alias.br
#         value: branch
#         scope: global

#     - git_config:
#         name: alias.st
#         value: status
#         scope: global

#     - git_config:
#         name: alias.hist
#         value: log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'
#         scope: global

#     - git_config:
#         name: alias.type
#         value: cat-file -t
#         scope: global

#     - git_config:
#         name: alias.dump
#         value: cat-file -p
#         scope: global

#     - git_config:
#         name: alias.diffc
#         value: diff --cached
#         scope: global

#     - git_config:
#         name: color.ui
#         value: auto
#         scope: global
