---
- hosts: localhost
  tasks:

  - name: Update apt
    shell: apt update
    become: true

  - name: Install maven
    package:
      name: maven
      state: latest
    become: true

  - name: Create dir for settings file
    file:
      path:  ~/.m2
      state: directory
      mode: 0755

  - name: Hackish download of scripts from another Docker build
    get_url:
      url: "{{ item }}"
      dest: "{{ ansible_user_dir }}/.m2/settings.xml"
      mode: 0644
    with_items:
      - http://git.spk.no/projects/INFRA/repos/base-java-build/raw/settings/settings.xml?at=refs%2Fheads%2Fmaster
