import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [{type: 'autogenerated', dirName: '.'}],
};

// noinspection JSUnusedGlobalSymbols -- loaded by Docusaurus via sidebarPath at runtime
export default sidebars;
