alias pri="cd ~/src/privat"
alias dot="cd ~/.dotfiles"
alias fit="cd ~/src/spk/config/fitnesse-install-linux"

alias spk="cd ~/src/spk"
alias pev="cd ~/src/spk/pensjonsvedtak"
alias puma="cd ~/src/spk/puma-tjenestemoduler"
alias pudat="cd ~/src/spk/puma-tjenestemoduler/pensjon-database"
alias pupev="cd ~/src/spk/puma-tjenestemoduler/pensjonsvedtak"
alias pusam="cd ~/src/spk/puma-tjenestemoduler/samhandling"
