name: Link check

on:
  push:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    name: Check links in markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --verbose --include-fragments '**/*.md'
          fail: true
