name: Link check

on:
  push:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    name: Check links in markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --verbose --include-fragments '**/*.md'
          fail: true
