name: Test dotfiles installation on Ubuntu
on: [ push ]

jobs:
  build:
    name: TestOnUbuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: bash -c "./bin/dotfiles -p"